### ISSUE TITLE
Issue with react

### ISSUE THREAD

**Issue by PolGuixe** [babel/generator-babel-boilerplate#424]
When I do `npm run build`, I get this error:

```
[23:09:32] Starting 'lint-src'...
[23:09:32] Starting 'lint-test'...
[23:09:32] Starting 'lint-gulpfile'...
[23:09:32] Starting 'clean'...
[23:09:32] Finished 'clean' after 22 ms
[23:09:32] Finished 'lint-src' after 408 ms
[23:09:32] Finished 'lint-gulpfile' after 219 ms
[23:09:32] Finished 'lint-test' after 276 ms
[23:09:32] Starting 'lint'...
[23:09:32] Finished 'lint' after 5.98 μs
[23:09:32] Starting 'build'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./src/ContainerFluid.jsx
Module parse failed: /Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/src/ContainerFluid.jsx Unexpected token (25:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (25:6)
    at Parser.pp$4.raise (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/Users/PolGuixe/Documents/Developer/Meteor/Packages/npm/react-flexbox-grid-jss/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
 @ ./src/react-flexbox-grid-jss.js 12:22-53./src/Container.jsx
```

The `unexpected token` is the `<`in `<div>...` inside here: 

```
class Container extends React.PureComponent {
  render() {
    return (
      <div className={this.props.classes.container}>
        {this.props.children}
      </div>
    );
  }
}
```

I do have the babel-react preset installed and this is my `.babelrc`:
```
{
  "presets": [
    "latest",
    "stage-2",
    "react"
  ],
  "env": {
    "tests": {
      "plugins": ["babel-plugin-rewire"]
    }
  }
}
```

**Comment by jmeas** [comment]
@PolGuixe interesting...I'd expect that to work. Is this project on GitHub, by chance?

**Comment by jmeas** [comment]
Ah okay, i see the problem. This boilerplate (currently) only loads the babel loader for .js files, and not .jsx. You'll need to update this line:

`{test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'}`

to match jsx files as well. I'll add this to the FAQ.

For now, i'm going to close this issue. Let me know if you need more help.

**Comment by PolGuixe** [comment]
I've added this line: 
```
          {test: /\.jsx$/, exclude: /node_modules/, loader: 'babel-loader'}
```
In the gulp config file:
```
    module: {
        loaders: [
          {test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
          {test: /\.jsx$/, exclude: /node_modules/, loader: 'babel-loader'}
        ]
      },
```

And now works.
